# Generated by Django 3.2 on 2021-06-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0004_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
