# Generated by Django 3.2 on 2021-06-28 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0005_alter_api_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='updatetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
