# Generated by Django 3.2 on 2021-06-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0006_api_updatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='pointsteamlist',
            field=models.JSONField(default=dict),
        ),
    ]
