# Generated by Django 3.2 on 2021-06-29 11:10

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0007_api_pointsteamlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='pointsteamlist',
            field=models.CharField(max_length=500, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
