# Generated by Django 3.2 on 2021-06-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0008_alter_api_pointsteamlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='pointsteamlist',
            field=models.CharField(max_length=500),
        ),
    ]
