# Generated by Django 3.2 on 2021-07-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0009_alter_api_pointsteamlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='updatetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Updated at'),
        ),
    ]
