# Generated by Django 3.2 on 2021-07-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0010_alter_api_updatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
